"""노션 페스티벌 리스트 기반 NOTION_ 레코드 상세 정보 시드."""
import logging
from datetime import datetime

from app.domains.performance.application.port.performance_repository_port import PerformanceRepositoryPort
from app.domains.performance.domain.entity.performance import Performance

logger = logging.getLogger(__name__)

# 울산서머페스티벌, JUMF 전주얼티밋 제외
NOTION_FESTIVALS: list[dict] = [
    {
        "mt20id": "NOTION_015",
        "prfnm": "그린캠프 페스티벌",
        "prfpdfrom": "2026.04.18",
        "prfpdto": "2026.04.19",
        "fcltynm": "지산포레스트 리조트",
        "pcseguidance": "1일권 109,000원, 이천시민 98,100원",
        "genrenm": "락/인디",
        "prfstate": "공연예정",
        "area": "경기도",
        "festival": "Y",
        "relates": [{"name": "네이버예약", "url": "https://booking.naver.com/booking/12/bizes/1582267/items/7375234"}],
    },
    {
        "mt20id": "NOTION_016",
        "prfnm": "KT&G 상상실현 페스티벌",
        "prfpdfrom": "2026.04.11",
        "prfpdto": "2026.04.12",
        "fcltynm": "KT&G 상상마당 춘천 아트센터",
        "pcseguidance": "1일권 66,000원, 춘천시민 44,000원",
        "genrenm": "락/인디",
        "prfstate": "공연예정",
        "area": "강원특별자치도",
        "festival": "Y",
        "relates": [{"name": "YES24", "url": "https://ticket.yes24.com/Perf/57153"}],
    },
    {
        "mt20id": "NOTION_017",
        "prfnm": "2026 통영프린지 페스티벌",
        "prfpdfrom": "2026.03.20",
        "prfpdto": "2026.04.04",
        "fcltynm": "통영 시내 야외 무대",
        "pcseguidance": "무료",
        "genrenm": "복합",
        "prfstate": "공연중",
        "area": "경상남도",
        "festival": "Y",
        "relates": [],
    },
    {
        "mt20id": "NOTION_018",
        "prfnm": "LOUD BRIDGE FESTIVAL SEOUL 2026(라우드 브릿지 페스티벌)",
        "prfpdfrom": "2026.04.11",
        "prfpdto": "2026.04.12",
        "fcltynm": "예스24 라이브홀",
        "pcseguidance": "1일권 132,000원",
        "genrenm": "락/인디",
        "prfstate": "공연예정",
        "area": "서울특별시",
        "festival": "Y",
        "relates": [{"name": "YES24", "url": "https://ticket.yes24.com/Perf/56040"}],
    },
    {
        "mt20id": "NOTION_019",
        "prfnm": "2026 체리블라썸뮤직페스티벌",
        "prfpdfrom": "2026.04.04",
        "prfpdto": "2026.04.05",
        "fcltynm": "진해공설운동장",
        "pcseguidance": "1일권 110,000원, 양일권 170,000원",
        "genrenm": "락/인디",
        "prfstate": "공연예정",
        "area": "경상남도",
        "festival": "Y",
        "relates": [{"name": "인터파크", "url": "https://tickets.interpark.com/goods/26000906"}],
    },
    {
        "mt20id": "NOTION_020",
        "prfnm": "2026 LOVESOME(러브썸)",
        "prfpdfrom": "2026.04.11",
        "prfpdto": "2026.04.12",
        "fcltynm": "연세대학교 신촌캠퍼스 노천극장",
        "pcseguidance": "1일권 110,000원",
        "genrenm": "락/인디",
        "prfstate": "공연예정",
        "area": "서울특별시",
        "festival": "Y",
        "relates": [{"name": "네이버예약", "url": "https://booking.naver.com/booking/12/bizes/1589949"}],
    },
    {
        "mt20id": "NOTION_021",
        "prfnm": "워터밤 부산 2026",
        "prfpdfrom": "2026.08.08",
        "prfpdto": "2026.08.08",
        "fcltynm": "추후 공개",
        "pcseguidance": "2차 티켓 99,000원",
        "genrenm": "EDM",
        "prfstate": "공연예정",
        "area": "부산광역시",
        "festival": "Y",
        "relates": [{"name": "워터밤", "url": "https://www.waterbombfestival.com/ticket-busan"}],
    },
    {
        "mt20id": "NOTION_022",
        "prfnm": "THE AIR HOUSE",
        "prfpdfrom": "2026.05.23",
        "prfpdto": "2026.05.25",
        "fcltynm": "남이섬",
        "pcseguidance": "토-일 140,000원, 일-월 120,000원, 토-월 170,000원",
        "genrenm": "복합",
        "prfstate": "공연예정",
        "area": "강원특별자치도",
        "festival": "Y",
        "relates": [
            {"name": "공식사이트", "url": "https://www.the-airhouse.com/"},
            {"name": "KREAM", "url": "https://kream.co.kr/exhibitions/theairhouse2026"},
        ],
    },
    # --- 기존 NOTION_ 레코드 상세 업데이트 ---
    {
        "mt20id": "NOTION_001",
        "prfnm": "서울 파크 뮤직 페스티벌",
        "prfpdfrom": "2026.06.20",
        "prfpdto": "2026.06.21",
        "fcltynm": "올림픽공원 88잔디마당/티켓링크 라이브 아레나",
        "pcseguidance": "1일권 119,000원",
        "genrenm": "락/인디",
        "prfstate": "공연예정",
        "area": "서울특별시",
        "festival": "Y",
        "relates": [{"name": "인터파크", "url": "https://tickets.interpark.com/goods/26003322"}],
    },
    {
        "mt20id": "NOTION_002",
        "prfnm": "아시안 팝 페스티벌 2026",
        "prfpdfrom": "2026.05.30",
        "prfpdto": "2026.05.31",
        "fcltynm": "인천 파라다이스시티",
        "pcseguidance": "1일권 110,000원, 양일권 176,000원",
        "genrenm": "힙합, EDM",
        "prfstate": "공연예정",
        "area": "인천광역시",
        "festival": "Y",
        "relates": [{"name": "인터파크", "url": "https://tickets.interpark.com/goods/25018300"}],
    },
    {
        "mt20id": "NOTION_004",
        "prfnm": "PEAK FESTIVAL(피크 페스티벌) 2026",
        "prfpdfrom": "2026.05.23",
        "prfpdto": "2026.05.24",
        "fcltynm": "서울 난지한강 공원",
        "pcseguidance": "1일권 110,000원, 양일권 149,000원",
        "genrenm": "락/인디",
        "prfstate": "공연예정",
        "area": "서울특별시",
        "festival": "Y",
        "relates": [{"name": "티켓링크", "url": "https://www.ticketlink.co.kr/product/61484"}],
    },
    {
        "mt20id": "NOTION_005",
        "prfnm": "HIPHOPPLAYA FESTIVAL(힙합플레이야 페스티벌) 2026",
        "prfpdfrom": "2026.05.02",
        "prfpdto": "2026.05.02",
        "fcltynm": "킨텍스 제2전시장",
        "pcseguidance": "일반 149,000원, 프리미엄 239,000원",
        "genrenm": "힙합",
        "prfstate": "공연예정",
        "area": "경기도",
        "festival": "Y",
        "relates": [{"name": "YES24", "url": "https://ticket.yes24.com/Perf/57387"}],
    },
    {
        "mt20id": "NOTION_006",
        "prfnm": "2026 WORLD DJ FESTIVAL(월드 디제이 페스티벌)",
        "prfpdfrom": "2026.06.13",
        "prfpdto": "2026.06.14",
        "fcltynm": "서울랜드",
        "pcseguidance": "1일권 169,000원, 양일권 299,000원",
        "genrenm": "EDM",
        "prfstate": "공연예정",
        "area": "경기도",
        "festival": "Y",
        "relates": [
            {"name": "공식사이트", "url": "https://wdjfest.com/"},
            {"name": "인터파크", "url": "https://tickets.interpark.com/goods/25011306"},
        ],
    },
    {
        "mt20id": "NOTION_009",
        "prfnm": "부산국제록페스티벌 2026",
        "prfpdfrom": "2026.10.02",
        "prfpdto": "2026.10.04",
        "fcltynm": "삼락생태공원",
        "pcseguidance": "미정",
        "genrenm": "락/인디, EDM",
        "prfstate": "공연예정",
        "area": "부산광역시",
        "festival": "Y",
        "relates": [{"name": "공식사이트", "url": "https://busanrockfestival.com/"}],
    },
    {
        "mt20id": "NOTION_010",
        "prfnm": "인천펜타포트락페스티벌 2026",
        "prfpdfrom": "2026.07.31",
        "prfpdto": "2026.08.02",
        "fcltynm": "송도달빛축제공원",
        "pcseguidance": "미정",
        "genrenm": "락/인디",
        "prfstate": "공연예정",
        "area": "인천광역시",
        "festival": "Y",
        "relates": [{"name": "공식사이트", "url": "https://www.pentaport.co.kr/"}],
    },
    {
        "mt20id": "NOTION_012",
        "prfnm": "2026 EDC KOREA",
        "prfpdfrom": "2026.10.03",
        "prfpdto": "2026.10.04",
        "fcltynm": "인스파이어 엔터테인먼트 리조트",
        "pcseguidance": "GA 2day 210,000원, VIP 2day 310,000원",
        "genrenm": "EDM",
        "prfstate": "공연예정",
        "area": "인천광역시",
        "festival": "Y",
        "relates": [
            {"name": "공식사이트", "url": "https://korea.electricdaisycarnival.com/"},
            {"name": "티켓", "url": "https://korea.electricdaisycarnival.com/tickets/"},
        ],
    },
    {
        "mt20id": "NOTION_014",
        "prfnm": "RAPBEAT(랩비트) 2026",
        "prfpdfrom": "2026.06.20",
        "prfpdto": "2026.06.21",
        "fcltynm": "문화비축기지",
        "pcseguidance": "1일권 99,000원, 블라인드 양일권 89,000원",
        "genrenm": "힙합",
        "prfstate": "공연예정",
        "area": "서울특별시",
        "festival": "Y",
        "relates": [{"name": "공식사이트", "url": "https://rapbeatfestival.com/"}],
    },
]

# 새로 추가된 NOTION_ 레코드용 포스터 URL
POSTER_URLS: dict[str, str] = {
    "NOTION_015": "https://ticketimage.interpark.com/Play/image/large/26/26000869_p.gif",
    "NOTION_016": "https://tkfile.yes24.com/upload2/PerfBlog/202602/20260211/20260211-57153_1.jpg",
    "NOTION_017": "https://img1.newsis.com/2026/03/15/NISI20260315_0002083914_web.jpg",
    "NOTION_018": "https://tkfile.yes24.com/upload2/PerfBlog/202601/20260108/20260108-56040.jpg",
    "NOTION_019": "https://www.cbmfestival.com/theme/cbmfestival/img/ticket-poster.jpeg",
    "NOTION_020": "https://image.edaily.co.kr/images/Photo/files/NP/S/2026/01/PS26012100442.jpg",
    "NOTION_021": "https://image.toast.com/aaaaab/ticketlink/TKL_6/WB26_Busan_main_0227.jpg",
    "NOTION_022": "https://trommelmusic.com/wp-content/uploads/2024/05/Screenshot-2024-05-01-at-21.15.31.png",
}


class SeedNotionDetailsUseCase:

    def __init__(self, performance_repo: PerformanceRepositoryPort) -> None:
        self._performance_repo = performance_repo

    async def execute(self) -> int:
        now = datetime.utcnow()
        count = 0
        for data in NOTION_FESTIVALS:
            existing = await self._performance_repo.find_by_id(data["mt20id"])
            poster = existing.poster if existing and existing.poster else POSTER_URLS.get(data["mt20id"], "")
            perf = Performance(
                mt20id=data["mt20id"],
                prfnm=data["prfnm"],
                prfpdfrom=data["prfpdfrom"],
                prfpdto=data["prfpdto"],
                fcltynm=data["fcltynm"],
                pcseguidance=data.get("pcseguidance", ""),
                genrenm=data.get("genrenm", ""),
                prfstate=data.get("prfstate", ""),
                area=data.get("area", ""),
                festival=data.get("festival", "Y"),
                relates=data.get("relates", []),
                poster=poster,
                updated_at=now,
            )
            await self._performance_repo.save(perf)
            count += 1
            logger.info("시드 완료: %s (%s)", data["mt20id"], data["prfnm"])
        return count
